### ISSUE TITLE
repo URL broken

### ISSUE THREAD

**Issue by IndrajeetPatil** [MangoTheCat/testCoverage#14]
The URL for this repo-
http://www.mango-solutions.com/wp/products-services/r-services/r-packages/testcoverage/
gives 404 error.

**Comment by dougmet** [comment]
Hi there. We really like testCoverage but other packages, most notably [covr](https://github.com/r-lib/covr), pulled too far ahead so we've stopped support for this package. Details here: https://www.mango-solutions.com/blog/covr-a-victory-for-open-source-2

I've updated the URL to point to a proper link, and I've added a repo status badge to indicated that it's no longer supported.
